// packages/web/src/components/MentionPopup.tsx
interface MentionCandidate {
  handle: string; displayName: string; type: "user" | "agent"; id: string;
}

interface Props {
  items: MentionCandidate[];
  selectedIdx: number;
  position: { top: number; left: number };
  onSelect: (handle: string) => void;
  onClose: () => void;
}

export function MentionPopup({ items, selectedIdx, position, onSelect, onClose }: Props) {
  if (items.length === 0) return null;
  return (
    <div className="fixed z-50" style={{ bottom: window.innerHeight - position.top + 10 + "px", left: position.left + "px" }}
      onMouseLeave={onClose}>
      <div className="bg-gray-800 border border-gray-600 rounded-lg shadow-xl w-64 max-h-48 overflow-y-auto">
        {items.map((item, i) => (
          <button key={item.id || item.handle}
            onClick={() => onSelect(item.handle)}
            className={"w-full text-left px-3 py-2 flex items-center gap-2 text-sm " +
              (i === selectedIdx ? "bg-blue-600 text-white" : "text-gray-300 hover:bg-gray-700")}>
            <span className={"w-6 h-6 rounded flex items-center justify-center text-xs font-bold shrink-0 " +
              (item.type === "agent" ? "bg-purple-600" : "bg-gray-600")}>
              {item.handle[0]?.toUpperCase() || "?"}
            </span>
            <div className="min-w-0">
              <div className="truncate font-semibold">@{item.handle}</div>
              <div className="text-xs truncate opacity-70">{item.displayName} · {item.type === "agent" ? "Agent" : "User"}</div>
            </div>
          </button>
        ))}
      </div>
    </div>
  );
}

// packages/web/src/components/chat/MentionPopup.vue
<script setup lang="ts">
interface MentionCandidate {
  handle: string;
  displayName: string;
  type: "user" | "agent";
  id?: string;
}

defineProps<{
  items: MentionCandidate[];
  selectedIdx: number;
}>();

const emit = defineEmits<{
  select: [handle: string];
}>();
</script>

<template>
  <div
    v-if="items.length > 0"
    data-mention-popup
    class="absolute z-50 bg-gray-800 border border-gray-600 rounded-lg shadow-xl overflow-hidden"
    style="bottom: 100%; left: 1rem; min-width: 14rem; max-height: 15rem; overflow-y: auto; margin-bottom: 4px"
  >
    <button
      v-for="(item, i) in items"
      :key="item.handle"
      type="button"
      :class="[
        'w-full text-left px-3 py-1.5 text-sm flex items-center gap-2',
        i === selectedIdx ? 'bg-blue-600 text-white' : 'text-gray-300 hover:bg-gray-700',
      ]"
      @click="emit('select', item.handle)"
    >
      <span class="w-5 h-5 rounded-full bg-gray-600 flex items-center justify-center text-[10px] shrink-0">
        {{ (item.displayName || item.handle)[0] }}
      </span>
      <span class="font-medium truncate">@{{ item.handle }}</span>
      <span v-if="item.displayName && item.displayName !== item.handle" class="text-gray-500 text-xs truncate">
        {{ item.displayName }}
      </span>
      <span class="ml-auto text-[10px] opacity-50 shrink-0">
        {{ item.type === "agent" ? "Agent" : "" }}
      </span>
    </button>
  </div>
</template>
