// packages/web/src/components/ui/Card.tsx
import { type HTMLAttributes, type ReactNode } from "react";

interface CardProps extends HTMLAttributes<HTMLDivElement> {
  children: ReactNode;
  padding?: "none" | "sm" | "md" | "lg";
}

const paddingStyles = {
  none: "",
  sm: "p-3",
  md: "p-4",
  lg: "p-6",
};

export function Card({ children, padding = "md", className = "", ...props }: CardProps) {
  return (
    <div
      className={[
        "rounded-lg border border-gray-200 bg-gray-50 dark:border-gray-700 dark:bg-gray-800",
        paddingStyles[padding],
        className,
      ].join(" ")}
      {...props}
    >
      {children}
    </div>
  );
}

// packages/web-vue/src/components/ui/Card.vue
<script setup lang="ts">
type CardPadding = "none" | "sm" | "md" | "lg";

withDefaults(defineProps<{
  padding?: CardPadding;
}>(), {
  padding: "md",
});

const paddingStyles: Record<CardPadding, string> = {
  none: "",
  sm: "p-3",
  md: "p-4",
  lg: "p-6",
};
</script>

<template>
  <!-- 父级 class 与其余 div 属性（id / data-* 等）通过 fallthrough 落到根 div 上 -->
  <div
    :class="[
      'rounded-lg border border-gray-200 bg-gray-50 dark:border-gray-700 dark:bg-gray-800',
      paddingStyles[padding],
    ]"
  >
    <slot />
  </div>
</template>
