// packages/web-vue/src/pages/ForgotPasswordPage.vue
<script setup lang="ts">
import { ref } from "vue";
import { RouterLink } from "vue-router";
import { apiPost } from "../api";
import Card from "../components/ui/Card.vue";
import Input from "../components/ui/Input.vue";
import Button from "../components/ui/Button.vue";

const email = ref("");
const code = ref("");
const newPw = ref("");
const step = ref<"email" | "reset">("email");
const msg = ref("");
const err = ref("");
const loading = ref(false);

async function handleSendCode() {
  err.value = "";
  msg.value = "";
  if (!email.value.includes("@")) {
    err.value = "请输入有效邮箱";
    return;
  }
  loading.value = true;
  try {
    const data = await apiPost<{ message: string; devCode?: string }>("/api/auth/forgot-password", { email: email.value });
    msg.value = data.devCode ? `验证码（开发模式）: ${data.devCode}` : data.message;
    step.value = "reset";
  } catch (e: any) {
    err.value = e.message || "发送失败";
  } finally {
    loading.value = false;
  }
}

async function handleReset() {
  err.value = "";
  msg.value = "";
  if (newPw.value.length < 6) {
    err.value = "新密码至少 6 位";
    return;
  }
  loading.value = true;
  try {
    await apiPost("/api/auth/reset-password", { email: email.value, code: code.value, password: newPw.value });
    msg.value = "密码已重置！去登录吧。";
    step.value = "email";
  } catch (e: any) {
    err.value = e.message || "重置失败";
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div class="flex min-h-screen items-center justify-center bg-gray-50 p-4 dark:bg-gray-900">
    <Card padding="lg" class="w-full max-w-sm space-y-5">
      <div class="text-center">
        <h1 class="text-2xl font-bold text-gray-900 dark:text-white">找回密码</h1>
      </div>

      <div v-if="step === 'email'" class="space-y-4">
        <Input
          type="email"
          placeholder="注册邮箱"
          :value="email"
          @input="email = ($event.target as HTMLInputElement).value"
        />
        <Button class="w-full" :loading="loading" @click="handleSendCode">发送验证码</Button>
      </div>
      <div v-else class="space-y-4">
        <Input
          type="text"
          placeholder="6 位验证码"
          :value="code"
          @input="code = ($event.target as HTMLInputElement).value"
          maxlength="6"
        />
        <Input
          type="password"
          placeholder="新密码（至少6位）"
          :value="newPw"
          @input="newPw = ($event.target as HTMLInputElement).value"
        />
        <Button class="w-full" :loading="loading" @click="handleReset">重置密码</Button>
      </div>

      <p v-if="msg" class="text-center text-sm text-green-600 dark:text-green-400">{{ msg }}</p>
      <p v-if="err" class="text-center text-sm text-red-500">{{ err }}</p>
      <p class="text-center text-sm text-gray-500 dark:text-gray-400">
        <RouterLink to="/login" class="text-blue-500 hover:underline">返回登录</RouterLink>
      </p>
    </Card>
  </div>
</template>

// packages/web/src/pages/ForgotPasswordPage.tsx
import { useState } from "react";
import { Link } from "react-router-dom";
import { apiPost } from "../api/client";
import { Button } from "../components/ui/Button";
import { Card } from "../components/ui/Card";
import { Input } from "../components/ui/Input";

export function ForgotPasswordPage() {
  const [email, setEmail] = useState("");
  const [code, setCode] = useState("");
  const [newPw, setNewPw] = useState("");
  const [step, setStep] = useState<"email" | "reset">("email");
  const [msg, setMsg] = useState("");
  const [err, setErr] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSendCode = async () => {
    setErr("");
    setMsg("");
    if (!email.includes("@")) {
      setErr("请输入有效邮箱");
      return;
    }
    setLoading(true);
    try {
      const data = await apiPost<{ message: string; devCode?: string }>("/api/auth/forgot-password", { email });
      setMsg(data.devCode ? `验证码（开发模式）: ${data.devCode}` : data.message);
      setStep("reset");
    } catch (e: any) {
      setErr(e.message || "发送失败");
    } finally {
      setLoading(false);
    }
  };

  const handleReset = async () => {
    setErr("");
    setMsg("");
    if (newPw.length < 6) {
      setErr("新密码至少 6 位");
      return;
    }
    setLoading(true);
    try {
      await apiPost("/api/auth/reset-password", { email, code, password: newPw });
      setMsg("密码已重置！去登录吧。");
      setStep("email");
    } catch (e: any) {
      setErr(e.message || "重置失败");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-50 p-4 dark:bg-gray-900">
      <Card padding="lg" className="w-full max-w-sm space-y-5">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white">找回密码</h1>
        </div>

        {step === "email" ? (
          <div className="space-y-4">
            <Input type="email" placeholder="注册邮箱" value={email} onChange={(e) => setEmail(e.target.value)} />
            <Button onClick={handleSendCode} loading={loading} className="w-full">
              发送验证码
            </Button>
          </div>
        ) : (
          <div className="space-y-4">
            <Input
              type="text"
              placeholder="6 位验证码"
              value={code}
              onChange={(e) => setCode(e.target.value)}
              maxLength={6}
            />
            <Input
              type="password"
              placeholder="新密码（至少6位）"
              value={newPw}
              onChange={(e) => setNewPw(e.target.value)}
            />
            <Button onClick={handleReset} loading={loading} className="w-full">
              重置密码
            </Button>
          </div>
        )}

        {msg && <p className="text-center text-sm text-green-600 dark:text-green-400">{msg}</p>}
        {err && <p className="text-center text-sm text-red-500">{err}</p>}
        <p className="text-center text-sm text-gray-500 dark:text-gray-400">
          <Link to="/login" className="text-blue-500 hover:underline">
            返回登录
          </Link>
        </p>
      </Card>
    </div>
  );
}
