// packages/web/src/components/ui/Input.tsx
import { forwardRef, type InputHTMLAttributes } from "react";

interface InputProps extends InputHTMLAttributes<HTMLInputElement> {}

export const Input = forwardRef<HTMLInputElement, InputProps>(
  ({ className = "", ...props }, ref) => {
    return (
      <input
        ref={ref}
        className={[
          "w-full rounded-md border border-gray-300 bg-gray-100 px-3 py-2 text-sm text-gray-900 placeholder:text-gray-400",
          "focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/30",
          "dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder:text-gray-500",
          "disabled:cursor-not-allowed disabled:opacity-50",
          className,
        ].join(" ")}
        {...props}
      />
    );
  }
);
Input.displayName = "Input";

// packages/web/src/components/ui/Input.vue
<script setup lang="ts">
import { ref } from "vue";

// 纯样式包装：value / onInput / placeholder / type 等原生属性与父级 class 全部 fallthrough 到 input。
// 对齐 React 受控写法：父组件用 :value + @input（Input 不支持 v-model）。
const el = ref<HTMLInputElement | null>(null);

function focus() {
  el.value?.focus();
}

// 对齐 React forwardRef：父组件模板 ref 上可直接访问 el（已解包为 DOM 元素）与 focus()
defineExpose({ el, focus });
</script>

<template>
  <input
    ref="el"
    :class="[
      'w-full rounded-md border border-gray-300 bg-gray-100 px-3 py-2 text-sm text-gray-900 placeholder:text-gray-400',
      'focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/30',
      'dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder:text-gray-500',
      'disabled:cursor-not-allowed disabled:opacity-50',
    ]"
  />
</template>
